export const SEARCH_PATIENTS = 'SEARCH_PATIENTS';
export const GET_PATIENT = 'GET_PATIENT';
export const GET_RECORDS = 'GET_RECORDS';
export const CLEAR_PATIENTS = 'CLEAR_PATIENTS';
export const SET_LOADING = 'SET_LOADING';
